#!/usr/bin/env python3
from __future__ import annotations
import argparse,datetime as dt,json,subprocess,sys
from pathlib import Path
CHECKS=(
('documentation consistency','scripts/check_docs_consistency.py',[]),('OKF structure/resources','scripts/agentic/validate_okf.py',[]),('tool adapters','scripts/agentic/validate_agent_adapters.py',[]),('portable skills','scripts/agentic/validate_agent_skills.py',[]),('agentic references','scripts/agentic/validate_agentic_references.py',['--repo','{repo}']),('ADF status drift','scripts/agentic/validate_status_drift.py',['--repo','{repo}']),('canonical knowledge authority','scripts/agentic/validate_canonical_knowledge.py',['--repo','{repo}']),('CKR-B foundation semantic coverage','scripts/agentic/validate_ckr_b_foundation.py',['--repo','{repo}']),('CKR-C concept/SYN semantic coverage','scripts/agentic/validate_ckr_c_concepts.py',['--repo','{repo}']),('CKR-D evidence/authority semantic coverage','scripts/agentic/validate_ckr_d_evidence_authority.py',['--repo','{repo}']),('CKR-E health/quality semantic coverage','scripts/agentic/validate_ckr_e_health_quality.py',['--repo','{repo}']),('CKR-F operations semantic coverage','scripts/agentic/validate_ckr_f_operations.py',['--repo','{repo}']),('CKR-G experience semantic coverage','scripts/agentic/validate_ckr_g_experience.py',['--repo','{repo}']),('CKR-H integration semantic coverage','scripts/agentic/validate_ckr_h_integration.py',['--repo','{repo}']),('CKR-I architecture semantic coverage','scripts/agentic/validate_ckr_i_architecture.py',['--repo','{repo}']),('CKR-I architecture negative controls','scripts/agentic/test_ckr_i_architecture_guards.py',['--repo','{repo}']),('CKR-J routing/stable-reference coverage','scripts/agentic/validate_ckr_j_routing.py',['--repo','{repo}']),('CKR-J routing negative controls','scripts/agentic/test_ckr_j_routing_guards.py',['--repo','{repo}']),('CKR-K consolidation/provenance exit','scripts/agentic/validate_ckr_k_exit.py',['--repo','{repo}']),('CKR-K exit negative controls','scripts/agentic/test_ckr_k_exit_guards.py',['--repo','{repo}']),('CKR status drift','scripts/agentic/validate_ckr_status.py',['--repo','{repo}']),('fixture catalog','scripts/agentic/validate_fixture_catalog.py',['--repo','{repo}']),('context budgets','scripts/agentic/measure_context_budget.py',['{repo}']),('ADF-G compatibility evidence','scripts/agentic/validate_adf_g_compatibility.py',['--repo','{repo}']),('Databricks Agent Skills addendum','scripts/agentic/validate_databricks_agent_skills.py',['--repo','{repo}']),('agentic secret scan','scripts/agentic/scan_agentic_secrets.py',['--repo','{repo}']),('ADF-H security/lifecycle governance','scripts/agentic/validate_adf_h_governance.py',['--repo','{repo}']))
def knowledge_lifecycle(repo):
    deprecated=stale=0; today=dt.date.today()
    for path in (repo/'knowledge').rglob('*.md'):
        text=path.read_text(encoding='utf-8'); deprecated+=int('status: "deprecated"' in text or 'status: deprecated' in text)
        for line in text.splitlines():
            if line.startswith('stale_after:'):
                raw=line.split(':',1)[1].strip().strip("\"'")[:10]
                try: stale+=int(dt.date.fromisoformat(raw)<=today)
                except ValueError: pass
    return deprecated,stale
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--repo',default='.'); ap.add_argument('--report'); ap.add_argument('--skip-negative-controls',action='store_true'); args=ap.parse_args(); repo=Path(args.repo).resolve(); results=[]
    for name,rel,extra in CHECKS:
        cmd=[sys.executable,str(repo/rel)]+[x.format(repo=str(repo)) for x in extra]; p=subprocess.run(cmd,cwd=repo,text=True,capture_output=True); out=(p.stdout+p.stderr).strip(); results.append((name,p.returncode,out)); print(('PASS' if p.returncode==0 else 'FAIL'),name); print(out) if out else None
    if not args.skip_negative_controls:
        p=subprocess.run([sys.executable,str(repo/'scripts/agentic/test_conformance_guards.py'),'--repo',str(repo)],cwd=repo,text=True,capture_output=True); out=(p.stdout+p.stderr).strip(); results.append(('negative controls',p.returncode,out)); print(('PASS' if p.returncode==0 else 'FAIL'),'negative controls'); print(out) if out else None
    compat=json.loads((repo/'docs/agentic_development_foundation/tool_compatibility.json').read_text())['tools']; deprecated,stale=knowledge_lifecycle(repo); overall='PASS' if all(c==0 for _,c,_ in results) else 'FAIL'
    lines=['# Agentic Conformance Report','',f'**Agentic configuration conformance:** {overall}','','> This report describes repository agentic/documentation-authority configuration health only. It is not DMTZ domain health, data quality, source health, or production readiness.','','## Checks','','| Check | Result |','|---|---|']+[f'| {n} | {"PASS" if c==0 else "FAIL"} |' for n,c,_ in results]+['','## Tool compatibility state','']
    for tool,data in compat.items(): lines.append(f'- **{tool}:** `{data.get("support_status","unknown")}` / runtime `{data.get("runtime_status","unknown")}`')
    lines+=['','## Knowledge lifecycle','',f'- Deprecated knowledge entries: **{deprecated}**',f'- Stale knowledge entries: **{stale}**','','## Notes','','- Provider tool-in-the-loop runtime verification remains independent per tool; ADF-EX-17 is deferred under the bounded progression exception.','- CKR changes documentation authority/routing, not accepted DMTZ semantics; Implementation 001-A follows the live CKR status authority and is never started by conformance.','- CKR-B protects the canonical foundation/glossary cutover.','- CKR-C protects the 24-concept catalog and SYN-001–SYN-035.','- CKR-D protects REF-001–REF-030, AUTH-001–AUTH-053 and the authority vocabulary.','- CKR-E protects HLTH-001–HLTH-066 from omission, health-axis collapse, blind propagation and readiness/control conflation.','- CKR-F protects OPS-001–OPS-123 from omission, topology/status propagation, plan/runtime collapse, localization/causal shortcuts, exposure/Impact collapse and Gate/Safeguard conflation.','- CKR-G protects EXPL-001–EXPL-160 from truth/projection collapse, confidence scoring, negative-evidence dilution, disclosure overstatement, sibling-state propagation and historical-view rewriting.','- CKR-H protects INTG-001–INTG-270 from source-availability/authority collapse, timestamp-based joins, negative-evidence dilution, runtime/version overclaiming, Lineage/exposure/Impact collapse, control overstatement and historical-replay rewriting.','- CKR-I protects ARCH-001–ARCH-500 and the frozen reference architecture from deployment-capability shortcuts, persistence/source-authority collapse, join/version overclaiming, derived-store/model truth leakage, historical replay rewriting, Gate/Safeguard lifecycle collapse and runtime convenience becoming domain truth.','- CKR-J protects canonical-first OKF routing, deterministic owner-path::stable-ID resolution, separate history discovery, agent routing alignment and routing-drift enforcement without becoming semantic authority.','- CKR-K protects whole-retrofit ownership closure, provenance/history preservation, current-truth locality, dual-authority exclusion and the implementation-gate handoff without changing product semantics.','- `docs/canonical/` becomes current semantic authority only through the CKR inventory and atomic cutover contract.','- Databricks vendor skills remain reviewed operational dependencies, not semantic authority.','- Agentic secret scanning is a high-confidence repository guard, not organization-wide secret scanning.','']
    report='\n'.join(lines)
    if args.report:
        out=Path(args.report); out=out if out.is_absolute() else repo/out; out.write_text(report,encoding='utf-8')
    print(report); return 0 if overall=='PASS' else 1
if __name__=='__main__': raise SystemExit(main())
